on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        uses: takanome-dev/hello-world-js-action@v1.1.2
        id: hello
        with:
          who-to-greet: 'Takanome the Open Source Guy'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
